#ifndef ___TOOLS_SVGA3D_TABLES_H___
#define ___TOOLS_SVGA3D_TABLES_H___

#include <stdint.h>
#include <stddef.h>
#include <string>
#include <vector>

#include <vmsvga/svga_reg.h>
#include <vmsvga/svga3d_reg.h>
#include <vmsvga/svga3d_caps.h>
#include <d3d9types.h>

struct DevCapInfo {
    uint32_t id;
    const char *name;
    const char *desc;
    uint32_t expectedValue;
    int expectedRc;
};

struct SurfaceFormatInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dFormat;
    const char *d3dFormatName;
    uint32_t vkFormat;
    const char *vkFormatName;
};

struct RenderStateInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dState;
    const char *d3dStateName;
};

struct TextureStageStateInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dType;
    const char *d3dTypeName;
};

struct TextureCombinerInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dOp;
    const char *d3dOpName;
};

struct TextureAddressInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dAddress;
    const char *d3dAddressName;
};

struct PrimitiveTypeInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dType;
    const char *d3dTypeName;
    uint32_t vkTopology;
    const char *vkTopologyName;
};

struct BlendOpInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dOp;
    const char *d3dOpName;
};

struct CmpFuncInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dFunc;
    const char *d3dFuncName;
};

struct StencilOpInfo {
    uint32_t id;
    const char *name;
    uint32_t d3dOp;
    const char *d3dOpName;
};

/* Vulkan format constants matching standard Vulkan 1.0/1.1 */
#ifndef VK_FORMAT_UNDEFINED
#define VK_FORMAT_UNDEFINED 0
#define VK_FORMAT_B8G8R8A8_UNORM 44
#define VK_FORMAT_B8G8R8A8_SRGB 45
#define VK_FORMAT_R8G8B8A8_UNORM 37
#define VK_FORMAT_B5G6R5_UNORM_PACK16 84
#define VK_FORMAT_B5G5R5A1_UNORM_PACK16 86
#define VK_FORMAT_B4G4R4A4_UNORM_PACK16 80
#define VK_FORMAT_D32_SFLOAT 126
#define VK_FORMAT_D16_UNORM 124
#define VK_FORMAT_D24_UNORM_S8_UINT 129
#define VK_FORMAT_R8_UNORM 9
#define VK_FORMAT_R8G8_UNORM 16
#define VK_FORMAT_R16_UNORM 70
#define VK_FORMAT_R16G16_UNORM 77
#define VK_FORMAT_BC1_RGBA_UNORM_BLOCK 133
#define VK_FORMAT_BC2_UNORM_BLOCK 135
#define VK_FORMAT_BC3_UNORM_BLOCK 137
#define VK_FORMAT_BC4_UNORM_BLOCK 139
#define VK_FORMAT_BC5_UNORM_BLOCK 141
#define VK_FORMAT_R16G16B16A16_SFLOAT 97
#define VK_FORMAT_R32G32B32A32_SFLOAT 109
#define VK_FORMAT_A2R10G10B10_UNORM_PACK32 64
#define VK_FORMAT_R16_SFLOAT 76
#define VK_FORMAT_R32_SFLOAT 100
#define VK_FORMAT_R16G16_SFLOAT 83
#define VK_FORMAT_R32G32_SFLOAT 103
#endif

/* Vulkan Primitive Topology constants */
#ifndef VK_PRIMITIVE_TOPOLOGY_POINT_LIST
#define VK_PRIMITIVE_TOPOLOGY_POINT_LIST 0
#define VK_PRIMITIVE_TOPOLOGY_LINE_LIST 1
#define VK_PRIMITIVE_TOPOLOGY_LINE_STRIP 2
#define VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST 3
#define VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP 4
#define VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN 5
#endif

/* All SVGA3D Device Capabilities (0 .. 83) */
static const DevCapInfo g_DevCaps[] = {
    { SVGA3D_DEVCAP_3D, "SVGA3D_DEVCAP_3D", "3D acceleration available", 1, 0 },
    { SVGA3D_DEVCAP_MAX_LIGHTS, "SVGA3D_DEVCAP_MAX_LIGHTS", "Maximum active lights", 8, 0 },
    { SVGA3D_DEVCAP_MAX_TEXTURES, "SVGA3D_DEVCAP_MAX_TEXTURES", "Maximum simultaneous textures", 8, 0 },
    { SVGA3D_DEVCAP_MAX_CLIP_PLANES, "SVGA3D_DEVCAP_MAX_CLIP_PLANES", "Maximum user clip planes", 6, 0 },
    { SVGA3D_DEVCAP_VERTEX_SHADER_VERSION, "SVGA3D_DEVCAP_VERTEX_SHADER_VERSION", "Vertex shader version", 0x300, 0 },
    { SVGA3D_DEVCAP_VERTEX_SHADER, "SVGA3D_DEVCAP_VERTEX_SHADER", "Vertex shader support boolean", 1, 0 },
    { SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION, "SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION", "Pixel shader version", 0x300, 0 },
    { SVGA3D_DEVCAP_FRAGMENT_SHADER, "SVGA3D_DEVCAP_FRAGMENT_SHADER", "Pixel shader support boolean", 1, 0 },
    { SVGA3D_DEVCAP_MAX_RENDER_TARGETS, "SVGA3D_DEVCAP_MAX_RENDER_TARGETS", "Simultaneous render targets", 4, 0 },
    { SVGA3D_DEVCAP_S23E8_TEXTURES, "SVGA3D_DEVCAP_S23E8_TEXTURES", "32-bit float texture format", 0, -2 },
    { SVGA3D_DEVCAP_S10E5_TEXTURES, "SVGA3D_DEVCAP_S10E5_TEXTURES", "16-bit float texture format", 0, -2 },
    { SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND, "SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND", "Fixed-function vertex blending matrices", 4, 0 },
    { SVGA3D_DEVCAP_D16_BUFFER_FORMAT, "SVGA3D_DEVCAP_D16_BUFFER_FORMAT", "16-bit depth buffer format", 1, 0 },
    { SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT, "SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT", "24-bit depth 8-bit stencil buffer", 1, 0 },
    { SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT, "SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT", "24-bit depth buffer", 1, 0 },
    { SVGA3D_DEVCAP_QUERY_TYPES, "SVGA3D_DEVCAP_QUERY_TYPES", "Supported query types bitmask", 1, 0 },
    { SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING, "SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING", "Texture gradient sampling support", 1, 0 },
    { SVGA3D_DEVCAP_MAX_POINT_SIZE, "SVGA3D_DEVCAP_MAX_POINT_SIZE", "Maximum point size", 256, 0 },
    { SVGA3D_DEVCAP_MAX_SHADER_TEXTURES, "SVGA3D_DEVCAP_MAX_SHADER_TEXTURES", "Maximum textures accessible in shaders", 0, -2 },
    { SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH, "SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH", "Maximum texture width", 8192, 0 },
    { SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT, "SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT", "Maximum texture height", 8192, 0 },
    { SVGA3D_DEVCAP_MAX_VOLUME_EXTENT, "SVGA3D_DEVCAP_MAX_VOLUME_EXTENT", "Maximum 3D volume extent", 2048, 0 },
    { SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT, "SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT", "Maximum texture repeat count", 8192, 0 },
    { SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO, "SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO", "Maximum texture aspect ratio", 8192, 0 },
    { SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY, "SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY", "Maximum texture anisotropy", 16, 0 },
    { SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT, "SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT", "Maximum primitives per draw call", 0x100000, 0 },
    { SVGA3D_DEVCAP_MAX_VERTEX_INDEX, "SVGA3D_DEVCAP_MAX_VERTEX_INDEX", "Maximum vertex index value", 0xffffff, 0 },
    { SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS, "SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS", "Max VS instructions", 4096, 0 },
    { SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS, "SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS", "Max PS instructions", 4096, 0 },
    { SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS, "SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS", "Max VS temporary registers", 32, 0 },
    { SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS, "SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS", "Max PS temporary registers", 32, 0 },
    { SVGA3D_DEVCAP_TEXTURE_OPS, "SVGA3D_DEVCAP_TEXTURE_OPS", "Supported texture stage combiners bitmask", 0x03ffffff, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8, "SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8", "Format X8R8G8B8 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8, "SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8", "Format A8R8G8B8 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10, "SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10", "Format A2R10G10B10 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5, "SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5", "Format X1R5G5B5 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5, "SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5", "Format A1R5G5B5 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4, "SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4", "Format A4R4G4B4 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_R5G6B5, "SVGA3D_DEVCAP_SURFACEFMT_R5G6B5", "Format R5G6B5 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16, "SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16", "Format LUMINANCE16 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8, "SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8", "Format LUMINANCE8_ALPHA8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_ALPHA8, "SVGA3D_DEVCAP_SURFACEFMT_ALPHA8", "Format ALPHA8 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8, "SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8", "Format LUMINANCE8 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_D16, "SVGA3D_DEVCAP_SURFACEFMT_Z_D16", "Format Z_D16 capability flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8, "SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8", "Format Z_D24S8 capability flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8, "SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8", "Format Z_D24X8 capability flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_DXT1, "SVGA3D_DEVCAP_SURFACEFMT_DXT1", "Format DXT1 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_DXT2, "SVGA3D_DEVCAP_SURFACEFMT_DXT2", "Format DXT2 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_DXT3, "SVGA3D_DEVCAP_SURFACEFMT_DXT3", "Format DXT3 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_DXT4, "SVGA3D_DEVCAP_SURFACEFMT_DXT4", "Format DXT4 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_DXT5, "SVGA3D_DEVCAP_SURFACEFMT_DXT5", "Format DXT5 capability flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8, "SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8", "Format BUMPX8L8V8U8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10, "SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10", "Format A2W10V10U10 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8, "SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8", "Format BUMPU8V8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8, "SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8", "Format Q8W8V8U8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_CxV8U8, "SVGA3D_DEVCAP_SURFACEFMT_CxV8U8", "Format CxV8U8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_R_S10E5, "SVGA3D_DEVCAP_SURFACEFMT_R_S10E5", "Format R_S10E5 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_R_S23E8, "SVGA3D_DEVCAP_SURFACEFMT_R_S23E8", "Format R_S23E8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5, "SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5", "Format RG_S10E5 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8, "SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8", "Format RG_S23E8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5, "SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5", "Format ARGB_S10E5 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8, "SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8", "Format ARGB_S23E8 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES, "SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES", "Max VS texture units", 4, 0 },
    { SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS, "SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS", "Max simultaneous RTs", 4, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_V16U16, "SVGA3D_DEVCAP_SURFACEFMT_V16U16", "Format V16U16 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_G16R16, "SVGA3D_DEVCAP_SURFACEFMT_G16R16", "Format G16R16 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16, "SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16", "Format A16B16G16R16 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_UYVY, "SVGA3D_DEVCAP_SURFACEFMT_UYVY", "Format UYVY flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_YUY2, "SVGA3D_DEVCAP_SURFACEFMT_YUY2", "Format YUY2 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_MULTISAMPLE_NONMASKABLESAMPLES, "SVGA3D_DEVCAP_MULTISAMPLE_NONMASKABLESAMPLES", "Nonmaskable MSAA mask", 0x0, 0 },
    { SVGA3D_DEVCAP_MULTISAMPLE_MASKABLESAMPLES, "SVGA3D_DEVCAP_MULTISAMPLE_MASKABLESAMPLES", "Maskable MSAA samples bitmask", 0x14, 0 },
    { SVGA3D_DEVCAP_ALPHATOCOVERAGE, "SVGA3D_DEVCAP_ALPHATOCOVERAGE", "Alpha to coverage support", 1, 0 },
    { SVGA3D_DEVCAP_SUPERSAMPLE, "SVGA3D_DEVCAP_SUPERSAMPLE", "Supersample support", 1, 0 },
    { SVGA3D_DEVCAP_AUTOGENMIPMAPS, "SVGA3D_DEVCAP_AUTOGENMIPMAPS", "Automatic mipmap generation support", 1, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_NV12, "SVGA3D_DEVCAP_SURFACEFMT_NV12", "Format NV12 flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_AYUV, "SVGA3D_DEVCAP_SURFACEFMT_AYUV", "Format AYUV flags", 0x4f, 0 },
    { SVGA3D_DEVCAP_MAX_CONTEXT_IDS, "SVGA3D_DEVCAP_MAX_CONTEXT_IDS", "Maximum context ID space", 256, 0 },
    { SVGA3D_DEVCAP_MAX_SURFACE_IDS, "SVGA3D_DEVCAP_MAX_SURFACE_IDS", "Maximum surface ID space", 1024, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_DF16, "SVGA3D_DEVCAP_SURFACEFMT_Z_DF16", "Format Z_DF16 flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_DF24, "SVGA3D_DEVCAP_SURFACEFMT_Z_DF24", "Format Z_DF24 flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT, "SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT", "Format Z_D24S8_INT flags", 0x10, 0 },
    { SVGA3D_DEVCAP_SURFACEFMT_BC4_UNORM, "SVGA3D_DEVCAP_SURFACEFMT_BC4_UNORM", "Format BC4_UNORM flags", 0, -2 },
    { SVGA3D_DEVCAP_SURFACEFMT_BC5_UNORM, "SVGA3D_DEVCAP_SURFACEFMT_BC5_UNORM", "Format BC5_UNORM flags", 0, -2 },
};

/* Surface Formats Mapping */
static const SurfaceFormatInfo g_SurfaceFormats[] = {
    { SVGA3D_X8R8G8B8, "SVGA3D_X8R8G8B8", D3DFMT_X8R8G8B8, "D3DFMT_X8R8G8B8", VK_FORMAT_B8G8R8A8_UNORM, "VK_FORMAT_B8G8R8A8_UNORM" },
    { SVGA3D_A8R8G8B8, "SVGA3D_A8R8G8B8", D3DFMT_A8R8G8B8, "D3DFMT_A8R8G8B8", VK_FORMAT_B8G8R8A8_UNORM, "VK_FORMAT_B8G8R8A8_UNORM" },
    { SVGA3D_R5G6B5, "SVGA3D_R5G6B5", D3DFMT_R5G6B5, "D3DFMT_R5G6B5", VK_FORMAT_B5G6R5_UNORM_PACK16, "VK_FORMAT_B5G6R5_UNORM_PACK16" },
    { SVGA3D_X1R5G5B5, "SVGA3D_X1R5G5B5", D3DFMT_X1R5G5B5, "D3DFMT_X1R5G5B5", VK_FORMAT_B5G5R5A1_UNORM_PACK16, "VK_FORMAT_B5G5R5A1_UNORM_PACK16" },
    { SVGA3D_A1R5G5B5, "SVGA3D_A1R5G5B5", D3DFMT_A1R5G5B5, "D3DFMT_A1R5G5B5", VK_FORMAT_B5G5R5A1_UNORM_PACK16, "VK_FORMAT_B5G5R5A1_UNORM_PACK16" },
    { SVGA3D_A4R4G4B4, "SVGA3D_A4R4G4B4", D3DFMT_A4R4G4B4, "D3DFMT_A4R4G4B4", VK_FORMAT_B4G4R4A4_UNORM_PACK16, "VK_FORMAT_B4G4R4A4_UNORM_PACK16" },
    { SVGA3D_Z_D32, "SVGA3D_Z_D32", D3DFMT_D32, "D3DFMT_D32", VK_FORMAT_D32_SFLOAT, "VK_FORMAT_D32_SFLOAT" },
    { SVGA3D_Z_D16, "SVGA3D_Z_D16", D3DFMT_D16, "D3DFMT_D16", VK_FORMAT_D16_UNORM, "VK_FORMAT_D16_UNORM" },
    { SVGA3D_Z_D24S8, "SVGA3D_Z_D24S8", D3DFMT_D24S8, "D3DFMT_D24S8", VK_FORMAT_D24_UNORM_S8_UINT, "VK_FORMAT_D24_UNORM_S8_UINT" },
    { SVGA3D_Z_D15S1, "SVGA3D_Z_D15S1", D3DFMT_D15S1, "D3DFMT_D15S1", VK_FORMAT_D16_UNORM, "VK_FORMAT_D16_UNORM" },
    { SVGA3D_LUMINANCE8, "SVGA3D_LUMINANCE8", D3DFMT_L8, "D3DFMT_L8", VK_FORMAT_R8_UNORM, "VK_FORMAT_R8_UNORM" },
    { SVGA3D_LUMINANCE4_ALPHA4, "SVGA3D_LUMINANCE4_ALPHA4", D3DFMT_A4L4, "D3DFMT_A4L4", VK_FORMAT_R8_UNORM, "VK_FORMAT_R8_UNORM" },
    { SVGA3D_LUMINANCE16, "SVGA3D_LUMINANCE16", D3DFMT_L16, "D3DFMT_L16", VK_FORMAT_R16_UNORM, "VK_FORMAT_R16_UNORM" },
    { SVGA3D_LUMINANCE8_ALPHA8, "SVGA3D_LUMINANCE8_ALPHA8", D3DFMT_A8L8, "D3DFMT_A8L8", VK_FORMAT_R8G8_UNORM, "VK_FORMAT_R8G8_UNORM" },
    { SVGA3D_DXT1, "SVGA3D_DXT1", D3DFMT_DXT1, "D3DFMT_DXT1", VK_FORMAT_BC1_RGBA_UNORM_BLOCK, "VK_FORMAT_BC1_RGBA_UNORM_BLOCK" },
    { SVGA3D_DXT2, "SVGA3D_DXT2", D3DFMT_DXT2, "D3DFMT_DXT2", VK_FORMAT_BC2_UNORM_BLOCK, "VK_FORMAT_BC2_UNORM_BLOCK" },
    { SVGA3D_DXT3, "SVGA3D_DXT3", D3DFMT_DXT3, "D3DFMT_DXT3", VK_FORMAT_BC2_UNORM_BLOCK, "VK_FORMAT_BC2_UNORM_BLOCK" },
    { SVGA3D_DXT4, "SVGA3D_DXT4", D3DFMT_DXT4, "D3DFMT_DXT4", VK_FORMAT_BC3_UNORM_BLOCK, "VK_FORMAT_BC3_UNORM_BLOCK" },
    { SVGA3D_DXT5, "SVGA3D_DXT5", D3DFMT_DXT5, "D3DFMT_DXT5", VK_FORMAT_BC3_UNORM_BLOCK, "VK_FORMAT_BC3_UNORM_BLOCK" },
    { SVGA3D_BUMPU8V8, "SVGA3D_BUMPU8V8", D3DFMT_V8U8, "D3DFMT_V8U8", VK_FORMAT_R8G8_UNORM, "VK_FORMAT_R8G8_UNORM" },
    { SVGA3D_BUMPL6V5U5, "SVGA3D_BUMPL6V5U5", D3DFMT_L6V5U5, "D3DFMT_L6V5U5", VK_FORMAT_UNDEFINED, "VK_FORMAT_UNDEFINED" },
    { SVGA3D_BUMPX8L8V8U8, "SVGA3D_BUMPX8L8V8U8", D3DFMT_X8L8V8U8, "D3DFMT_X8L8V8U8", VK_FORMAT_B8G8R8A8_UNORM, "VK_FORMAT_B8G8R8A8_UNORM" },
    { SVGA3D_BUMPL8V8U8, "SVGA3D_BUMPL8V8U8", D3DFMT_UNKNOWN, "D3DFMT_UNKNOWN", VK_FORMAT_UNDEFINED, "VK_FORMAT_UNDEFINED" },
    { SVGA3D_ARGB_S10E5, "SVGA3D_ARGB_S10E5", D3DFMT_A16B16G16R16F, "D3DFMT_A16B16G16R16F", VK_FORMAT_R16G16B16A16_SFLOAT, "VK_FORMAT_R16G16B16A16_SFLOAT" },
    { SVGA3D_ARGB_S23E8, "SVGA3D_ARGB_S23E8", D3DFMT_A32B32G32R32F, "D3DFMT_A32B32G32R32F", VK_FORMAT_R32G32B32A32_SFLOAT, "VK_FORMAT_R32G32B32A32_SFLOAT" },
    { SVGA3D_A2R10G10B10, "SVGA3D_A2R10G10B10", D3DFMT_A2R10G10B10, "D3DFMT_A2R10G10B10", VK_FORMAT_A2R10G10B10_UNORM_PACK32, "VK_FORMAT_A2R10G10B10_UNORM_PACK32" },
    { SVGA3D_V8U8, "SVGA3D_V8U8", D3DFMT_V8U8, "D3DFMT_V8U8", VK_FORMAT_R8G8_UNORM, "VK_FORMAT_R8G8_UNORM" },
    { SVGA3D_Q8W8V8U8, "SVGA3D_Q8W8V8U8", D3DFMT_Q8W8V8U8, "D3DFMT_Q8W8V8U8", VK_FORMAT_R8G8B8A8_UNORM, "VK_FORMAT_R8G8B8A8_UNORM" },
    { SVGA3D_CxV8U8, "SVGA3D_CxV8U8", D3DFMT_CxV8U8, "D3DFMT_CxV8U8", VK_FORMAT_R8G8_UNORM, "VK_FORMAT_R8G8_UNORM" },
    { SVGA3D_X8L8V8U8, "SVGA3D_X8L8V8U8", D3DFMT_X8L8V8U8, "D3DFMT_X8L8V8U8", VK_FORMAT_B8G8R8A8_UNORM, "VK_FORMAT_B8G8R8A8_UNORM" },
    { SVGA3D_A2W10V10U10, "SVGA3D_A2W10V10U10", D3DFMT_A2W10V10U10, "D3DFMT_A2W10V10U10", VK_FORMAT_A2R10G10B10_UNORM_PACK32, "VK_FORMAT_A2R10G10B10_UNORM_PACK32" },
    { SVGA3D_ALPHA8, "SVGA3D_ALPHA8", D3DFMT_A8, "D3DFMT_A8", VK_FORMAT_R8_UNORM, "VK_FORMAT_R8_UNORM" },
    { SVGA3D_R_S10E5, "SVGA3D_R_S10E5", D3DFMT_R16F, "D3DFMT_R16F", VK_FORMAT_R16_SFLOAT, "VK_FORMAT_R16_SFLOAT" },
    { SVGA3D_R_S23E8, "SVGA3D_R_S23E8", D3DFMT_R32F, "D3DFMT_R32F", VK_FORMAT_R32_SFLOAT, "VK_FORMAT_R32_SFLOAT" },
    { SVGA3D_RG_S10E5, "SVGA3D_RG_S10E5", D3DFMT_G16R16F, "D3DFMT_G16R16F", VK_FORMAT_R16G16_SFLOAT, "VK_FORMAT_R16G16_SFLOAT" },
    { SVGA3D_RG_S23E8, "SVGA3D_RG_S23E8", D3DFMT_G32R32F, "D3DFMT_G32R32F", VK_FORMAT_R32G32_SFLOAT, "VK_FORMAT_R32G32_SFLOAT" },
    { SVGA3D_BUFFER, "SVGA3D_BUFFER", D3DFMT_UNKNOWN, "D3DFMT_UNKNOWN", VK_FORMAT_UNDEFINED, "VK_FORMAT_UNDEFINED" },
    { SVGA3D_Z_D24X8, "SVGA3D_Z_D24X8", D3DFMT_D24X8, "D3DFMT_D24X8", VK_FORMAT_D24_UNORM_S8_UINT, "VK_FORMAT_D24_UNORM_S8_UINT" },
    { SVGA3D_V16U16, "SVGA3D_V16U16", D3DFMT_V16U16, "D3DFMT_V16U16", VK_FORMAT_R16G16_UNORM, "VK_FORMAT_R16G16_UNORM" },
    { SVGA3D_G16R16, "SVGA3D_G16R16", D3DFMT_G16R16, "D3DFMT_G16R16", VK_FORMAT_R16G16_UNORM, "VK_FORMAT_R16G16_UNORM" },
    { SVGA3D_A16B16G16R16, "SVGA3D_A16B16G16R16", D3DFMT_A16B16G16R16, "D3DFMT_A16B16G16R16", VK_FORMAT_R16G16B16A16_SFLOAT, "VK_FORMAT_R16G16B16A16_SFLOAT" },
    { SVGA3D_UYVY, "SVGA3D_UYVY", D3DFMT_UYVY, "D3DFMT_UYVY", VK_FORMAT_UNDEFINED, "VK_FORMAT_UNDEFINED" },
    { SVGA3D_YUY2, "SVGA3D_YUY2", D3DFMT_YUY2, "D3DFMT_YUY2", VK_FORMAT_UNDEFINED, "VK_FORMAT_UNDEFINED" },
    { SVGA3D_R8G8B8A8_UNORM, "SVGA3D_R8G8B8A8_UNORM", D3DFMT_A8B8G8R8, "D3DFMT_A8B8G8R8", VK_FORMAT_R8G8B8A8_UNORM, "VK_FORMAT_R8G8B8A8_UNORM" },
    { SVGA3D_BC4_UNORM, "SVGA3D_BC4_UNORM", D3DFMT_UNKNOWN, "D3DFMT_UNKNOWN", VK_FORMAT_BC4_UNORM_BLOCK, "VK_FORMAT_BC4_UNORM_BLOCK" },
    { SVGA3D_BC5_UNORM, "SVGA3D_BC5_UNORM", D3DFMT_UNKNOWN, "D3DFMT_UNKNOWN", VK_FORMAT_BC5_UNORM_BLOCK, "VK_FORMAT_BC5_UNORM_BLOCK" },
    { SVGA3D_Z_DF16, "SVGA3D_Z_DF16", D3DFMT_UNKNOWN, "D3DFMT_UNKNOWN", VK_FORMAT_D16_UNORM, "VK_FORMAT_D16_UNORM" },
    { SVGA3D_Z_DF24, "SVGA3D_Z_DF24", D3DFMT_D24FS8, "D3DFMT_D24FS8", VK_FORMAT_D24_UNORM_S8_UINT, "VK_FORMAT_D24_UNORM_S8_UINT" },
    { SVGA3D_Z_D24S8_INT, "SVGA3D_Z_D24S8_INT", D3DFMT_D24S8, "D3DFMT_D24S8", VK_FORMAT_D24_UNORM_S8_UINT, "VK_FORMAT_D24_UNORM_S8_UINT" },
};

/* Core Render States (SVGA3D_RS_* -> D3D9 D3DRENDERSTATETYPE) */
static const RenderStateInfo g_RenderStates[] = {
    { SVGA3D_RS_ZENABLE, "SVGA3D_RS_ZENABLE", D3DRS_ZENABLE, "D3DRS_ZENABLE" },
    { SVGA3D_RS_FILLMODE, "SVGA3D_RS_FILLMODE", D3DRS_FILLMODE, "D3DRS_FILLMODE" },
    { SVGA3D_RS_SHADEMODE, "SVGA3D_RS_SHADEMODE", D3DRS_SHADEMODE, "D3DRS_SHADEMODE" },
    { SVGA3D_RS_ZWRITEENABLE, "SVGA3D_RS_ZWRITEENABLE", D3DRS_ZWRITEENABLE, "D3DRS_ZWRITEENABLE" },
    { SVGA3D_RS_ALPHATESTENABLE, "SVGA3D_RS_ALPHATESTENABLE", D3DRS_ALPHATESTENABLE, "D3DRS_ALPHATESTENABLE" },
    { SVGA3D_RS_LASTPIXEL, "SVGA3D_RS_LASTPIXEL", D3DRS_LASTPIXEL, "D3DRS_LASTPIXEL" },
    { SVGA3D_RS_SRCBLEND, "SVGA3D_RS_SRCBLEND", D3DRS_SRCBLEND, "D3DRS_SRCBLEND" },
    { SVGA3D_RS_DSTBLEND, "SVGA3D_RS_DSTBLEND", D3DRS_DESTBLEND, "D3DRS_DESTBLEND" },
    { SVGA3D_RS_CULLMODE, "SVGA3D_RS_CULLMODE", D3DRS_CULLMODE, "D3DRS_CULLMODE" },
    { SVGA3D_RS_ZFUNC, "SVGA3D_RS_ZFUNC", D3DRS_ZFUNC, "D3DRS_ZFUNC" },
    { SVGA3D_RS_ALPHAFUNC, "SVGA3D_RS_ALPHAFUNC", D3DRS_ALPHAFUNC, "D3DRS_ALPHAFUNC" },
    { SVGA3D_RS_DITHERENABLE, "SVGA3D_RS_DITHERENABLE", D3DRS_DITHERENABLE, "D3DRS_DITHERENABLE" },
    { SVGA3D_RS_BLENDENABLE, "SVGA3D_RS_BLENDENABLE", D3DRS_ALPHABLENDENABLE, "D3DRS_ALPHABLENDENABLE" },
    { SVGA3D_RS_FOGENABLE, "SVGA3D_RS_FOGENABLE", D3DRS_FOGENABLE, "D3DRS_FOGENABLE" },
    { SVGA3D_RS_SPECULARENABLE, "SVGA3D_RS_SPECULARENABLE", D3DRS_SPECULARENABLE, "D3DRS_SPECULARENABLE" },
    { SVGA3D_RS_FOGCOLOR, "SVGA3D_RS_FOGCOLOR", D3DRS_FOGCOLOR, "D3DRS_FOGCOLOR" },
    { SVGA3D_RS_FOGMODE, "SVGA3D_RS_FOGMODE", D3DRS_FOGTABLEMODE, "D3DRS_FOGTABLEMODE" },
    { SVGA3D_RS_FOGSTART, "SVGA3D_RS_FOGSTART", D3DRS_FOGSTART, "D3DRS_FOGSTART" },
    { SVGA3D_RS_FOGEND, "SVGA3D_RS_FOGEND", D3DRS_FOGEND, "D3DRS_FOGEND" },
    { SVGA3D_RS_FOGDENSITY, "SVGA3D_RS_FOGDENSITY", D3DRS_FOGDENSITY, "D3DRS_FOGDENSITY" },
    { SVGA3D_RS_RANGEFOGENABLE, "SVGA3D_RS_RANGEFOGENABLE", D3DRS_RANGEFOGENABLE, "D3DRS_RANGEFOGENABLE" },
    { SVGA3D_RS_STENCILENABLE, "SVGA3D_RS_STENCILENABLE", D3DRS_STENCILENABLE, "D3DRS_STENCILENABLE" },
    { SVGA3D_RS_STENCILFAIL, "SVGA3D_RS_STENCILFAIL", D3DRS_STENCILFAIL, "D3DRS_STENCILFAIL" },
    { SVGA3D_RS_STENCILZFAIL, "SVGA3D_RS_STENCILZFAIL", D3DRS_STENCILZFAIL, "D3DRS_STENCILZFAIL" },
    { SVGA3D_RS_STENCILPASS, "SVGA3D_RS_STENCILPASS", D3DRS_STENCILPASS, "D3DRS_STENCILPASS" },
    { SVGA3D_RS_STENCILFUNC, "SVGA3D_RS_STENCILFUNC", D3DRS_STENCILFUNC, "D3DRS_STENCILFUNC" },
    { SVGA3D_RS_STENCILREF, "SVGA3D_RS_STENCILREF", D3DRS_STENCILREF, "D3DRS_STENCILREF" },
    { SVGA3D_RS_STENCILMASK, "SVGA3D_RS_STENCILMASK", D3DRS_STENCILMASK, "D3DRS_STENCILMASK" },
    { SVGA3D_RS_STENCILWRITEMASK, "SVGA3D_RS_STENCILWRITEMASK", D3DRS_STENCILWRITEMASK, "D3DRS_STENCILWRITEMASK" },
    { SVGA3D_RS_TEXTUREFACTOR, "SVGA3D_RS_TEXTUREFACTOR", D3DRS_TEXTUREFACTOR, "D3DRS_TEXTUREFACTOR" },
    { SVGA3D_RS_CLIPPING, "SVGA3D_RS_CLIPPING", D3DRS_CLIPPING, "D3DRS_CLIPPING" },
    { SVGA3D_RS_LIGHTINGENABLE, "SVGA3D_RS_LIGHTINGENABLE", D3DRS_LIGHTING, "D3DRS_LIGHTING" },
    { SVGA3D_RS_AMBIENT, "SVGA3D_RS_AMBIENT", D3DRS_AMBIENT, "D3DRS_AMBIENT" },
    { SVGA3D_RS_COLORWRITEENABLE, "SVGA3D_RS_COLORWRITEENABLE", D3DRS_COLORWRITEENABLE, "D3DRS_COLORWRITEENABLE" },
    { SVGA3D_RS_BLENDCOLOR, "SVGA3D_RS_BLENDCOLOR", D3DRS_BLENDFACTOR, "D3DRS_BLENDFACTOR" },
    { SVGA3D_RS_BLENDEQUATION, "SVGA3D_RS_BLENDEQUATION", D3DRS_BLENDOP, "D3DRS_BLENDOP" },
    { SVGA3D_RS_SCISSORTESTENABLE, "SVGA3D_RS_SCISSORTESTENABLE", D3DRS_SCISSORTESTENABLE, "D3DRS_SCISSORTESTENABLE" },
    { SVGA3D_RS_SLOPESCALEDEPTHBIAS, "SVGA3D_RS_SLOPESCALEDEPTHBIAS", D3DRS_SLOPESCALEDEPTHBIAS, "D3DRS_SLOPESCALEDEPTHBIAS" },
    { SVGA3D_RS_DEPTHBIAS, "SVGA3D_RS_DEPTHBIAS", D3DRS_DEPTHBIAS, "D3DRS_DEPTHBIAS" },
    { SVGA3D_RS_SEPARATEALPHABLENDENABLE, "SVGA3D_RS_SEPARATEALPHABLENDENABLE", D3DRS_SEPARATEALPHABLENDENABLE, "D3DRS_SEPARATEALPHABLENDENABLE" },
    { SVGA3D_RS_SRCBLENDALPHA, "SVGA3D_RS_SRCBLENDALPHA", D3DRS_SRCBLENDALPHA, "D3DRS_SRCBLENDALPHA" },
    { SVGA3D_RS_DSTBLENDALPHA, "SVGA3D_RS_DSTBLENDALPHA", D3DRS_DESTBLENDALPHA, "D3DRS_DESTBLENDALPHA" },
    { SVGA3D_RS_BLENDEQUATIONALPHA, "SVGA3D_RS_BLENDEQUATIONALPHA", D3DRS_BLENDOPALPHA, "D3DRS_BLENDOPALPHA" },
    { SVGA3D_RS_CCWSTENCILFAIL, "SVGA3D_RS_CCWSTENCILFAIL", D3DRS_CCW_STENCILFAIL, "D3DRS_CCW_STENCILFAIL" },
    { SVGA3D_RS_CCWSTENCILZFAIL, "SVGA3D_RS_CCWSTENCILZFAIL", D3DRS_CCW_STENCILZFAIL, "D3DRS_CCW_STENCILZFAIL" },
    { SVGA3D_RS_CCWSTENCILPASS, "SVGA3D_RS_CCWSTENCILPASS", D3DRS_CCW_STENCILPASS, "D3DRS_CCW_STENCILPASS" },
    { SVGA3D_RS_CCWSTENCILFUNC, "SVGA3D_RS_CCWSTENCILFUNC", D3DRS_CCW_STENCILFUNC, "D3DRS_CCW_STENCILFUNC" },
    { SVGA3D_RS_MULTISAMPLEANTIALIAS, "SVGA3D_RS_MULTISAMPLEANTIALIAS", D3DRS_MULTISAMPLEANTIALIAS, "D3DRS_MULTISAMPLEANTIALIAS" },
    { SVGA3D_RS_MULTISAMPLEMASK, "SVGA3D_RS_MULTISAMPLEMASK", D3DRS_MULTISAMPLEMASK, "D3DRS_MULTISAMPLEMASK" },
    { SVGA3D_RS_NORMALIZENORMALS, "SVGA3D_RS_NORMALIZENORMALS", D3DRS_NORMALIZENORMALS, "D3DRS_NORMALIZENORMALS" },
    { SVGA3D_RS_POINTSIZE, "SVGA3D_RS_POINTSIZE", D3DRS_POINTSIZE, "D3DRS_POINTSIZE" },
    { SVGA3D_RS_POINTSIZEMIN, "SVGA3D_RS_POINTSIZEMIN", D3DRS_POINTSIZE_MIN, "D3DRS_POINTSIZE_MIN" },
    { SVGA3D_RS_POINTSPRITEENABLE, "SVGA3D_RS_POINTSPRITEENABLE", D3DRS_POINTSPRITEENABLE, "D3DRS_POINTSPRITEENABLE" },
    { SVGA3D_RS_POINTSCALEENABLE, "SVGA3D_RS_POINTSCALEENABLE", D3DRS_POINTSCALEENABLE, "D3DRS_POINTSCALEENABLE" },
    { SVGA3D_RS_POINTSCALE_A, "SVGA3D_RS_POINTSCALE_A", D3DRS_POINTSCALE_A, "D3DRS_POINTSCALE_A" },
    { SVGA3D_RS_POINTSCALE_B, "SVGA3D_RS_POINTSCALE_B", D3DRS_POINTSCALE_B, "D3DRS_POINTSCALE_B" },
    { SVGA3D_RS_POINTSCALE_C, "SVGA3D_RS_POINTSCALE_C", D3DRS_POINTSCALE_C, "D3DRS_POINTSCALE_C" },
    { SVGA3D_RS_POINTSIZEMAX, "SVGA3D_RS_POINTSIZEMAX", D3DRS_POINTSIZE_MAX, "D3DRS_POINTSIZE_MAX" },
    { SVGA3D_RS_VERTEXMATERIALENABLE, "SVGA3D_RS_VERTEXMATERIALENABLE", D3DRS_INDEXEDVERTEXBLENDENABLE, "D3DRS_INDEXEDVERTEXBLENDENABLE" },
    { SVGA3D_RS_DIFFUSEMATERIALSOURCE, "SVGA3D_RS_DIFFUSEMATERIALSOURCE", D3DRS_DIFFUSEMATERIALSOURCE, "D3DRS_DIFFUSEMATERIALSOURCE" },
    { SVGA3D_RS_SPECULARMATERIALSOURCE, "SVGA3D_RS_SPECULARMATERIALSOURCE", D3DRS_SPECULARMATERIALSOURCE, "D3DRS_SPECULARMATERIALSOURCE" },
    { SVGA3D_RS_AMBIENTMATERIALSOURCE, "SVGA3D_RS_AMBIENTMATERIALSOURCE", D3DRS_AMBIENTMATERIALSOURCE, "D3DRS_AMBIENTMATERIALSOURCE" },
    { SVGA3D_RS_EMISSIVEMATERIALSOURCE, "SVGA3D_RS_EMISSIVEMATERIALSOURCE", D3DRS_EMISSIVEMATERIALSOURCE, "D3DRS_EMISSIVEMATERIALSOURCE" },
};

/* Primitive Topologies */
static const PrimitiveTypeInfo g_PrimitiveTypes[] = {
    { SVGA3D_PRIMITIVE_POINTLIST, "SVGA3D_PRIMITIVE_POINTLIST", D3DPT_POINTLIST, "D3DPT_POINTLIST", VK_PRIMITIVE_TOPOLOGY_POINT_LIST, "VK_PRIMITIVE_TOPOLOGY_POINT_LIST" },
    { SVGA3D_PRIMITIVE_LINELIST, "SVGA3D_PRIMITIVE_LINELIST", D3DPT_LINELIST, "D3DPT_LINELIST", VK_PRIMITIVE_TOPOLOGY_LINE_LIST, "VK_PRIMITIVE_TOPOLOGY_LINE_LIST" },
    { SVGA3D_PRIMITIVE_LINESTRIP, "SVGA3D_PRIMITIVE_LINESTRIP", D3DPT_LINESTRIP, "D3DPT_LINESTRIP", VK_PRIMITIVE_TOPOLOGY_LINE_STRIP, "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP" },
    { SVGA3D_PRIMITIVE_TRIANGLELIST, "SVGA3D_PRIMITIVE_TRIANGLELIST", D3DPT_TRIANGLELIST, "D3DPT_TRIANGLELIST", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST" },
    { SVGA3D_PRIMITIVE_TRIANGLESTRIP, "SVGA3D_PRIMITIVE_TRIANGLESTRIP", D3DPT_TRIANGLESTRIP, "D3DPT_TRIANGLESTRIP", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP" },
    { SVGA3D_PRIMITIVE_TRIANGLEFAN, "SVGA3D_PRIMITIVE_TRIANGLEFAN", D3DPT_TRIANGLEFAN, "D3DPT_TRIANGLEFAN", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN" },
};

/* Texture Combiner Ops */
static const TextureCombinerInfo g_TextureCombiners[] = {
    { SVGA3D_TC_DISABLE, "SVGA3D_TC_DISABLE", D3DTOP_DISABLE, "D3DTOP_DISABLE" },
    { SVGA3D_TC_SELECTARG1, "SVGA3D_TC_SELECTARG1", D3DTOP_SELECTARG1, "D3DTOP_SELECTARG1" },
    { SVGA3D_TC_SELECTARG2, "SVGA3D_TC_SELECTARG2", D3DTOP_SELECTARG2, "D3DTOP_SELECTARG2" },
    { SVGA3D_TC_MODULATE, "SVGA3D_TC_MODULATE", D3DTOP_MODULATE, "D3DTOP_MODULATE" },
    { SVGA3D_TC_MODULATE2X, "SVGA3D_TC_MODULATE2X", D3DTOP_MODULATE2X, "D3DTOP_MODULATE2X" },
    { SVGA3D_TC_MODULATE4X, "SVGA3D_TC_MODULATE4X", D3DTOP_MODULATE4X, "D3DTOP_MODULATE4X" },
    { SVGA3D_TC_ADD, "SVGA3D_TC_ADD", D3DTOP_ADD, "D3DTOP_ADD" },
    { SVGA3D_TC_ADDSIGNED, "SVGA3D_TC_ADDSIGNED", D3DTOP_ADDSIGNED, "D3DTOP_ADDSIGNED" },
    { SVGA3D_TC_ADDSIGNED2X, "SVGA3D_TC_ADDSIGNED2X", D3DTOP_ADDSIGNED2X, "D3DTOP_ADDSIGNED2X" },
    { SVGA3D_TC_SUBTRACT, "SVGA3D_TC_SUBTRACT", D3DTOP_SUBTRACT, "D3DTOP_SUBTRACT" },
    { SVGA3D_TC_ADDSMOOTH, "SVGA3D_TC_ADDSMOOTH", D3DTOP_ADDSMOOTH, "D3DTOP_ADDSMOOTH" },
    { SVGA3D_TC_BLENDDIFFUSEALPHA, "SVGA3D_TC_BLENDDIFFUSEALPHA", D3DTOP_BLENDDIFFUSEALPHA, "D3DTOP_BLENDDIFFUSEALPHA" },
    { SVGA3D_TC_BLENDTEXTUREALPHA, "SVGA3D_TC_BLENDTEXTUREALPHA", D3DTOP_BLENDTEXTUREALPHA, "D3DTOP_BLENDTEXTUREALPHA" },
    { SVGA3D_TC_BLENDFACTORALPHA, "SVGA3D_TC_BLENDFACTORALPHA", D3DTOP_BLENDFACTORALPHA, "D3DTOP_BLENDFACTORALPHA" },
    { SVGA3D_TC_BLENDTEXTUREALPHAPM, "SVGA3D_TC_BLENDTEXTUREALPHAPM", D3DTOP_BLENDTEXTUREALPHAPM, "D3DTOP_BLENDTEXTUREALPHAPM" },
    { SVGA3D_TC_BLENDCURRENTALPHA, "SVGA3D_TC_BLENDCURRENTALPHA", D3DTOP_BLENDCURRENTALPHA, "D3DTOP_BLENDCURRENTALPHA" },
    { SVGA3D_TC_PREMODULATE, "SVGA3D_TC_PREMODULATE", D3DTOP_PREMODULATE, "D3DTOP_PREMODULATE" },
    { SVGA3D_TC_MODULATEALPHA_ADDCOLOR, "SVGA3D_TC_MODULATEALPHA_ADDCOLOR", D3DTOP_MODULATEALPHA_ADDCOLOR, "D3DTOP_MODULATEALPHA_ADDCOLOR" },
    { SVGA3D_TC_MODULATECOLOR_ADDALPHA, "SVGA3D_TC_MODULATECOLOR_ADDALPHA", D3DTOP_MODULATECOLOR_ADDALPHA, "D3DTOP_MODULATECOLOR_ADDALPHA" },
    { SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR, "SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR", D3DTOP_MODULATEINVALPHA_ADDCOLOR, "D3DTOP_MODULATEINVALPHA_ADDCOLOR" },
    { SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA, "SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA", D3DTOP_MODULATEINVCOLOR_ADDALPHA, "D3DTOP_MODULATEINVCOLOR_ADDALPHA" },
    { SVGA3D_TC_DOTPRODUCT3, "SVGA3D_TC_DOTPRODUCT3", D3DTOP_DOTPRODUCT3, "D3DTOP_DOTPRODUCT3" },
    { SVGA3D_TC_MULTIPLYADD, "SVGA3D_TC_MULTIPLYADD", D3DTOP_MULTIPLYADD, "D3DTOP_MULTIPLYADD" },
    { SVGA3D_TC_LERP, "SVGA3D_TC_LERP", D3DTOP_LERP, "D3DTOP_LERP" },
};

/* Texture Addressing Modes */
static const TextureAddressInfo g_TextureAddresses[] = {
    { SVGA3D_TEX_ADDRESS_WRAP, "SVGA3D_TEX_ADDRESS_WRAP", D3DTADDRESS_WRAP, "D3DTADDRESS_WRAP" },
    { SVGA3D_TEX_ADDRESS_MIRROR, "SVGA3D_TEX_ADDRESS_MIRROR", D3DTADDRESS_MIRROR, "D3DTADDRESS_MIRROR" },
    { SVGA3D_TEX_ADDRESS_CLAMP, "SVGA3D_TEX_ADDRESS_CLAMP", D3DTADDRESS_CLAMP, "D3DTADDRESS_CLAMP" },
    { SVGA3D_TEX_ADDRESS_BORDER, "SVGA3D_TEX_ADDRESS_BORDER", D3DTADDRESS_BORDER, "D3DTADDRESS_BORDER" },
    { SVGA3D_TEX_ADDRESS_MIRRORONCE, "SVGA3D_TEX_ADDRESS_MIRRORONCE", D3DTADDRESS_MIRRORONCE, "D3DTADDRESS_MIRRORONCE" },
};

/* Blend Equations & Ops */
static const BlendOpInfo g_BlendOps[] = {
    { SVGA3D_BLENDOP_ZERO, "SVGA3D_BLENDOP_ZERO", D3DBLEND_ZERO, "D3DBLEND_ZERO" },
    { SVGA3D_BLENDOP_ONE, "SVGA3D_BLENDOP_ONE", D3DBLEND_ONE, "D3DBLEND_ONE" },
    { SVGA3D_BLENDOP_SRCCOLOR, "SVGA3D_BLENDOP_SRCCOLOR", D3DBLEND_SRCCOLOR, "D3DBLEND_SRCCOLOR" },
    { SVGA3D_BLENDOP_INVSRCCOLOR, "SVGA3D_BLENDOP_INVSRCCOLOR", D3DBLEND_INVSRCCOLOR, "D3DBLEND_INVSRCCOLOR" },
    { SVGA3D_BLENDOP_SRCALPHA, "SVGA3D_BLENDOP_SRCALPHA", D3DBLEND_SRCALPHA, "D3DBLEND_SRCALPHA" },
    { SVGA3D_BLENDOP_INVSRCALPHA, "SVGA3D_BLENDOP_INVSRCALPHA", D3DBLEND_INVSRCALPHA, "D3DBLEND_INVSRCALPHA" },
    { SVGA3D_BLENDOP_DESTALPHA, "SVGA3D_BLENDOP_DESTALPHA", D3DBLEND_DESTALPHA, "D3DBLEND_DESTALPHA" },
    { SVGA3D_BLENDOP_INVDESTALPHA, "SVGA3D_BLENDOP_INVDESTALPHA", D3DBLEND_INVDESTALPHA, "D3DBLEND_INVDESTALPHA" },
    { SVGA3D_BLENDOP_DESTCOLOR, "SVGA3D_BLENDOP_DESTCOLOR", D3DBLEND_DESTCOLOR, "D3DBLEND_DESTCOLOR" },
    { SVGA3D_BLENDOP_INVDESTCOLOR, "SVGA3D_BLENDOP_INVDESTCOLOR", D3DBLEND_INVDESTCOLOR, "D3DBLEND_INVDESTCOLOR" },
    { SVGA3D_BLENDOP_SRCALPHASAT, "SVGA3D_BLENDOP_SRCALPHASAT", D3DBLEND_SRCALPHASAT, "D3DBLEND_SRCALPHASAT" },
    { SVGA3D_BLENDOP_BLENDFACTOR, "SVGA3D_BLENDOP_BLENDFACTOR", D3DBLEND_BLENDFACTOR, "D3DBLEND_BLENDFACTOR" },
    { SVGA3D_BLENDOP_INVBLENDFACTOR, "SVGA3D_BLENDOP_INVBLENDFACTOR", D3DBLEND_INVBLENDFACTOR, "D3DBLEND_INVBLENDFACTOR" },
};

/* Comparison Functions */
static const CmpFuncInfo g_CmpFuncs[] = {
    { SVGA3D_CMP_NEVER, "SVGA3D_CMP_NEVER", D3DCMP_NEVER, "D3DCMP_NEVER" },
    { SVGA3D_CMP_LESS, "SVGA3D_CMP_LESS", D3DCMP_LESS, "D3DCMP_LESS" },
    { SVGA3D_CMP_EQUAL, "SVGA3D_CMP_EQUAL", D3DCMP_EQUAL, "D3DCMP_EQUAL" },
    { SVGA3D_CMP_LESSEQUAL, "SVGA3D_CMP_LESSEQUAL", D3DCMP_LESSEQUAL, "D3DCMP_LESSEQUAL" },
    { SVGA3D_CMP_GREATER, "SVGA3D_CMP_GREATER", D3DCMP_GREATER, "D3DCMP_GREATER" },
    { SVGA3D_CMP_NOTEQUAL, "SVGA3D_CMP_NOTEQUAL", D3DCMP_NOTEQUAL, "D3DCMP_NOTEQUAL" },
    { SVGA3D_CMP_GREATEREQUAL, "SVGA3D_CMP_GREATEREQUAL", D3DCMP_GREATEREQUAL, "D3DCMP_GREATEREQUAL" },
    { SVGA3D_CMP_ALWAYS, "SVGA3D_CMP_ALWAYS", D3DCMP_ALWAYS, "D3DCMP_ALWAYS" },
};

/* Stencil Operations */
static const StencilOpInfo g_StencilOps[] = {
    { SVGA3D_STENCILOP_KEEP, "SVGA3D_STENCILOP_KEEP", D3DSTENCILOP_KEEP, "D3DSTENCILOP_KEEP" },
    { SVGA3D_STENCILOP_ZERO, "SVGA3D_STENCILOP_ZERO", D3DSTENCILOP_ZERO, "D3DSTENCILOP_ZERO" },
    { SVGA3D_STENCILOP_REPLACE, "SVGA3D_STENCILOP_REPLACE", D3DSTENCILOP_REPLACE, "D3DSTENCILOP_REPLACE" },
    { SVGA3D_STENCILOP_INCRSAT, "SVGA3D_STENCILOP_INCRSAT", D3DSTENCILOP_INCRSAT, "D3DSTENCILOP_INCRSAT" },
    { SVGA3D_STENCILOP_DECRSAT, "SVGA3D_STENCILOP_DECRSAT", D3DSTENCILOP_DECRSAT, "D3DSTENCILOP_DECRSAT" },
    { SVGA3D_STENCILOP_INVERT, "SVGA3D_STENCILOP_INVERT", D3DSTENCILOP_INVERT, "D3DSTENCILOP_INVERT" },
    { SVGA3D_STENCILOP_INCR, "SVGA3D_STENCILOP_INCR", D3DSTENCILOP_INCR, "D3DSTENCILOP_INCR" },
    { SVGA3D_STENCILOP_DECR, "SVGA3D_STENCILOP_DECR", D3DSTENCILOP_DECR, "D3DSTENCILOP_DECR" },
};

#endif /* ___TOOLS_SVGA3D_TABLES_H___ */
